#!/bin/bash

# Switch to the directory to save the converted to .laz files into
cd ~/Mammoth/Scans

# Activate the PDAL environment
source ~/miniconda3/etc/profile.d/conda.sh
conda activate pdal

# Clone/convert all .rxp files into .laz using PDAL and its input config json file
find ~/Mammoth/Scans/ -name "*.rxp" | parallel pdal pipeline ~/Mammoth/Scripts/PDAL/base-laz.json --readers.rxp.filename={} --writers.las.filename={.}.laz

# Compress all original .rxp files
find  ~/Mammoth/Scans/ -name "*.rxp" | parallel gzip {}
