#!/bin/bash

lidarcollect=~/../home/mammoth/Mammoth/LidarCollect/build/LidarCollect
# Directory where we want to store the scan data files
cd /home/mammoth/Mammoth/Scans

# Conduct a basic line scan
$lidarcollect --ip 192.168.0.128 --line 1 30 130 0.04 195 30

# Wait for scanner to not be busy
sleep 10s

# Conduct a calibration/reference scan on the Spectralon panel.
$lidarcollect --ip 192.168.0.128 --line 1 115 125 0.02	276 30 spectralon

#wait for scanner to not be busy
sleep 10s
