#!/bin/bash

# Set pathing to work from any user
if [ ~ = "/root" ]; then
  PATH_PREFIX=~/../home/mammoth/mammoth
else
 # accessed via sudo perms or mammoth user
 PATH_PREFIX=~/mammoth
fi

# establish the directories we will be using based on user account
lidarcollect=$PATH_PREFIX/lidarcollect/build/lidarcollect

# make sure $1 has a value if no options are passed to script
if [[ -z "$1" ]]; then
  # $1 dne?
  OPTIONS="none"
else
  OPTIONS=$1
fi

#extract snowing status
if [ -e "$PATH_PREFIX""/scripts/vars/snowing" ]; then
  SNOWING=$(cat "$PATH_PREFIX""/scripts/vars/snowing")
else
  SNOWING=0
fi

# Directory where we want to store the scan data files
cd $PATH_PREFIX/scans

if [ $SNOWING = "1" ] || [ $OPTIONS = "manual" ] || [ $OPTIONS = "--manual" ]; then
  # Let the user know it is snowing and we are beginning a scan.
  echo "[EXTENDED]: It is snowing, extended line scan triggered."

  # Switch the power to on, for the scanner, if necessary.
  $PATH_PREFIX/scripts/gpio/scanner_poweron


  # Conduct an extended line scan
  $lidarcollect --ip 192.168.4.4 --line 1 30 130 0.04 185 150 extended

  # Wait for the scanner to not be busy
  sleep 10s
  
  # power down after scan so the power supply is not overdrawn.
  $PATH_PREFIX/scripts/gpio/scanner_poweroff

else
  # Let the user know it is not snowing and we are not beginning a scan.
  echo "[EXTENDED]: It is not snowing, extended line scan not triggered."
fi
