#!/bin/bash

# Set pathing to work from any user
if [ ~ = "/root" ]; then
  PATH_PREFIX=~/../home/mammoth/Mammoth
else
 # accessed via sudo perms or mammoth user
 PATH_PREFIX=~/Mammoth
fi

# establish the directories we will be using based on user account
lidarcollect=$PATH_PREFIX/LidarCollect/build/LidarCollect

#extract scanner power status
$PATH_PREFIX/Scripts/GPIO/scanner_status
PWR_VAL=$?

# make sure $1 has a value if no options are passed to script
if [[ -z "$1" ]]; then
  # $1 dne?
  OPTIONS="none"
else
  OPTIONS=$1
fi

#extract snowing status
if [ -e "$PATH_PREFIX""/Scripts/Vars/snowing" ]; then
  SNOWING=$(cat "$PATH_PREFIX""/Scripts/Vars/snowing")
else
  SNOWING=0
fi

# Directory where we want to store the scan data files
cd $PATH_PREFIX/Scans

if [ $SNOWING = "1" ] || [ $OPTIONS = "manual" ] || [ $OPTIONS = "--manual" ]; then
  # Let the user know it is snowing and we are beginning a scan.
  echo "[EXTENDED]: It is snowing, extended line scan triggered."

  # Switch the power to on, for the scanner, if necessary.
  if [ $PWR_VAL = "1" ]; then
    $PATH_PREFIX/Scripts/GPIO/scanner_poweron
  fi

  # Conduct an extended line scan
  $lidarcollect --ip 192.168.0.128 --line 1 30 130 0.04 185 150 extended

  # Wait for the scanner to not be busy
  sleep 10s

  minute=$(date +%M )
  if [ $minute -lt 10 ] || [ $OPTIONS = "manual" ] || [ $OPTIONS = "--manual" ]; then
    # Conduct a calibration/reference scan on the Spectralon panel.
    $lidarcollect --ip 192.168.0.128 --line 1 55 65 0.02 174 30 spectralon_extended

    # Wait for the scanner to not be busy
    sleep 10s
  fi

else
  # Let the user know it is not snowing and we are not beginning a scan.
  echo "[EXTENDED]: It is not snowing, extended line scan not triggered."
fi
