#!/bin/bash

# must run as sudo su -l root, so the pathing is correct.

# create symlinks for the scripts used in the A-TLS process.
ln -s ~/../home/mammoth/Mammoth/Scripts/AWS/syncaws ~/../home/mammoth/Mammoth/Symlinks/root/syncaws
ln -s ~/../home/mammoth/Mammoth/Scripts/GPIO/scanner_poweron ~/../home/mammoth/Mammoth/Symlinks/root/scanner_poweron
ln -s ~/../home/mammoth/Mammoth/Scripts/GPIO/scanner_poweroff ~/../home/mammoth/Mammoth/Symlinks/root/scanner_poweroff
ln -s ~/../home/mammoth/Mammoth/Scripts/GPIO/scanner_shutdown ~/../home/mammoth/Mammoth/Symlinks/root/scanner_shutdown
ln -s ~/../home/mammoth/Mammoth/Scripts/Logs/logs_split ~/../home/mammoth/Mammoth/Symlinks/root/logs_split
ln -s ~/../home/mammoth/Mammoth/Scripts/Scans/compress ~/../home/mammoth/Mammoth/Symlinks/root/compress
ln -s ~/../home/mammoth/Mammoth/Scripts/Scans/frame ~/../home/mammoth/Mammoth/Symlinks/root/frame
ln -s ~/../home/mammoth/Mammoth/Scripts/Scans/line ~/../home/mammoth/Mammoth/Symlinks/root/line
ln -s ~/../home/mammoth/Mammoth/Scripts/Scans/line_extended ~/../home/mammoth/Mammoth/Symlinks/root/line_extended
ln -s ~/../home/mammoth/Mammoth/Scripts/Vars/vars_init ~/../home/mammoth/Mammoth/Symlinks/root/vars_init
