#!/bin/bash

# Set pathing to work from any user
if [ ~ = "/root" ]; then
  PATH_PREFIX=~/../home/mammoth/mammoth
else
 # accessed via sudo perms or mammoth user
 PATH_PREFIX=~/mammoth
fi

# Set up GPO python pathing and commands.
GPO=$PATH_PREFIX/scripts/gpio/gpo_script
RELAY=2
CMD=STATUS

# Check the status of the pin, then extract GPO status from response
RESPONSE=$($GPO -c $CMD -r $RELAY)
VALUE=$(echo $RESPONSE | cut -b9-9)

if [[ -n $VALUE ]]; then
  if [ $VALUE = 0 ]; then
    # The pin is off
    echo "[LVX_STATUS]: GPO relay is off."
    exit 0
  elif [ $VALUE = 1 ]; then
    # The pin is on
    echo "[LVX_STATUS]: GPO relay is on."
    exit 1
  else
    # Invalid response
    echo "[LVX_STATUS]: Invalid response from gpo"
    exit 2
  fi 
else
  # Invalid response from status check or timeout?
  echo "[LVX_STATUS]: Error, worse..."
  exit 3
fi
