#!/bin/bash

# Set the path for the Fintek GPIO files.
GPIO=/sys/class/gpio/gpio80

# Initialize the Fintek GPIO if it has not been initialized already.
if [ ! -d "$GPIO" ]; then
   /usr/sbin/start_gpio start
fi

# Initialize Mammoth-A-TLS variables if it has not been done already.
if [ ! -d "/home/mammoth/Mammoth/Scripts/Vars" ]; then
  mkdir "/home/mammoth/Mammoth/Scripts/Vars"
fi
if [ ! -e "/home/mammoth/Mammoth/Scripts/Vars/scanner_power" ]; then
  touch "/home/mammoth/Mammoth/Scripts/Vars/scanner_power"
fi
if [ ! -e "/home/mammoth/Mammoth/Scripts/Vars/snowing" ]; then
  touch "/home/mammoth/Mammoth/Scripts/Vars/snowing"
fi

# Update GPIO pin values, in order to supply power to the scanner.
echo out >/sys/class/gpio/gpio80/direction
echo 0 >/sys/class/gpio/gpio80/value
echo 1 >/home/mammoth/Mammoth/Scripts/Vars/scanner_power

# wait for the scanner to boot up and respond to commands
sleep 240s

echo "Scanner On"
