#!/bin/bash

# Set pathing to work from any user
if [ ~ = "/root" ]; then
  PATH_PREFIX=~/../home/mammoth/mammoth
else
 # accessed via sudo perms or mammoth user
 PATH_PREFIX=~/mammoth
fi

# Define GPO python script and relay
GPO=$PATH_PREFIX/scripts/gpio/gpo_script
RELAY=1
CMD=ON

# Extract scanner power status
$PATH_PREFIX/scripts/gpio/scanner_status
PWR_VAL=$?

if [ $PWR_VAL = "1" ]; then
  # GPO is already providing +Vcc
  echo "[RGL_POWERON]: GPO already providing +Vcc."
elif [ $PWR_VAL = "0" ]; then
  # GPO is off, so let's go ahead and turn it on.
  $GPO -c $CMD -r $RELAY > /dev/null

  echo "[RGL_POWERON]: Scanner is warming up, press crtl+c to exit..."

  # wait for the scanner to boot up and respond to commands
  for i in {300..1}
  do
    echo -ne "\r$i""s remaining  "
    sleep 1
  done

  echo -ne "\r[RGL_POWERON]: Scanner On          \n"
else
  # Neither 0 or 1 was returned from status.
  echo "[POWERON]: Error, invalid response from status check."
fi
