#!/bin/bash

# Set pathing to work from any user
if [ ~ == "/root" ]; then
  PATH_PREFIX=~/../home/mammoth/Mammoth
else
 # accessed via sudo perms or mammoth user
 PATH_PREFIX=~/Mammoth
fi

# Set the path to the fintek gpio on/off tool
GPIO=$PATH_PREFIX/Fintek/demo_gpio

#extract scanner power status
$PATH_PREFIX/Scripts/GPIO/scanner_status
PWR_VAL=$?

if [ $PWR_VAL = "0" ]; then
  # power is on, okay to initiate power off commands.
  # Execute a scanner software shutdown before removing power.
  $PATH_PREFIX/Scripts/GPIO/scanner_shutdown

  # command only works with sudo privileges, accesses sys/class files.
  # demo_gpio <index> <direction> <mode> <value>
  # demo_gpio reg:0x80 dir:out mode:push val:high
  # A high gpio value connects the circuit to ground for output pins.
  $GPIO 0x80 1 1 1

  # Update GPIO pin values
  echo "[POWEROFF]: Scanner Off"
elif [ $PWR_VAL = "1" ]; then
  # gpio is off, try calling scanner_poweron first
  echo "[POWEROFF]: GPIO already disconnected."
else
  # run with insufficient permissions.
  echo "[POWEROFF]: Error, run with sudo or as root user."
fi
