#!/usr/bin/expect

send_user "SHUTDOWN: Attempting to shut down the scanner...\n"

set timeout 4

spawn telnet 192.168.4.4

expect {

        ">" {
                # printout error(s), if any
                send "Err()\r"

                expect {
                      "ERR()" {
                                # continue as normal
                      } timeout {
                                # there is an issue, but continue to shutdown.
                                send_user "SHUTDOWN: No response from scanner!\n"
                      }
                }
                
                # Add a return to park command prior to shutdown operation in case of stopped scan.
                sleep 3
                send "SCN_PARK()\r"
                expect {
                      "SCN_PARK()"{
                                # move to park position proceed as normal
                      } timeout {
                                # Unable to move to home, but continue shutdown.
                                send_user "SCN_PARK: No response from Scanner!\n"
                      }
                }

                # execute shutdown sequence after a short delay to get err() reponses.
                sleep 3
                send "shutdown()\r"

                expect {
                        eof {
                                send_user "SHUTDOWN: Scanner shutting down...\n"
                                sleep 60
                                send_user "SHUTDOWN: Scanner shut down.\n"
                                exit
                        } timeout {
                                send_user "SHUTDOWN: No eof, connection timed out...\n"
                                exit
                        }
                }

        } timeout {
                send_user "SHUTDOWN: No message returned from scanner...\n"
                exit
        }
}

wait
