#!/bin/bash

# generate the file prefix using YYYY_MM
file_prefix=$(date +"%Y_%m")
filename_root="$file_prefix""_root.log"
filename_mammoth="$file_prefix""_mammoth.log"

# if the directory we want to copy into does not exist, create it.
if [ ! -d "/home/mammoth/Mammoth/logs" ]; then
  mkdir "/home/mammoth/Mammoth/logs"
  mkdir "/home/mammoth/Mammoth/logs/root"
  mkdir "/home/mammoth/Mammoth/logs/mammoth"
fi

# copy the root/mammoth log into the new split log file.
cp /var/mail/root /home/mammoth/Mammoth/logs/root/$filename_root
echo "Mammoth mail log file has been split into a new month."
cp /var/mail/mammoth /home/mammoth/Mammoth/logs/mammoth/$filename_mammoth
echo "Root mail log file has been split into a new month."

# write the null character into the original files to clear it for a new month.
>/var/mail/root
>/var/mail/mammoth
