#!/bin/bash

# Set pathing to work from any user
if [ ~ = "/root" ]; then
  PATH_PREFIX=~/../home/mammoth/Mammoth
else
 # accessed via sudo perms or mammoth user
 PATH_PREFIX=~/Mammoth
fi

# Set the home path for the scan files and make sure it is accessible to children.
cd
export HOME=/home/mammoth
FILE_DIR=$PATH_PREFIX/Scans

# Set paths for original and converted file directories in the aws s3 bucket.
ORIGINAL=s3://crrel-mammoth-lidarscans/original_scans
CONVERTED=s3://crrel-mammoth-lidarscans/laz

# Move .gz and .laz files from the linux box to the AWS S3 bucket.
/usr/local/bin/./aws s3 mv $FILE_DIR $ORIGINAL --recursive --exclude "*" --include "*.gz"
/usr/local/bin/./aws s3 mv $FILE_DIR $CONVERTED --recursive --exclude "*" --include "*.laz"
